set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g detach-on-destroy off

bind h split-window -h
bind v split-window -v
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
