unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Make navigation easier.
set number
set cursorline
set laststatus=2

" Make search case-insensitive unless the query contains uppercase letters.
set ignorecase
set smartcase
set hlsearch

" Integrate yank and paste with the macOS clipboard.
set clipboard=unnamed

" Ask what to do when leaving a modified file.
set confirm
