# https://learn.chatgpt.com/docs/config-file/config-reference
# https://learn.chatgpt.com/docs/permissions

check_for_update_on_startup = false
default_permissions = "dev_workspace"
personality = "pragmatic"

[tui]
session_picker_view = "dense"
show_tooltips = false
status_line = ["model-with-reasoning", "current-dir", "context-remaining", "five-hour-limit", "weekly-limit", "thread-id"]
status_line_use_colors = true
theme = "catppuccin-macchiato"

[permissions.dev_workspace]
extends = ":workspace"

[permissions.dev_workspace.filesystem]
"~/.worktrees" = "write"
"~/.cache/uv" = "write"
"~/.cargo/.global-cache" = "write"
"~/.cargo/.package-cache-mutate" = "write"
"~/.cargo/.package-cache" = "write"
"~/.cargo/git" = "write"
"~/.cargo/registry" = "write"
"~/Library/Caches/pnpm" = "write"
"~/Library/pnpm/store" = "write"

# [permissions.dev_workspace.filesystem.":workspace_roots"]
# "**/*.env" = "deny"
# "**/config.local.fish" = "deny"

[permissions.dev_workspace.network]
enabled = false
# allow_local_binding = false
# enabled = true
# mode = "limited"

# [permissions.dev_workspace.network.domains]
# "crates.io" = "allow"
# "files.pythonhosted.org" = "allow"
# "index.crates.io" = "allow"
# "pypi.org" = "allow"
# "registry.npmjs.org" = "allow"
# "static.crates.io" = "allow"

[plugins."browser@openai-bundled"]
enabled = false

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."pdf@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[plugins."codex-tools@dotfiles"]
enabled = true

[features]
js_repl = false
memories = false
# network_proxy = true

[notice]
hide_rate_limit_model_nudge = true

[marketplaces.dotfiles]
source_type = "local"

[hooks.state]

[hooks.state."codex-tools@dotfiles:hooks/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:85159d2410a5a675c2d08ea083018fe71db682021e18f3778306bcf87b5c5cf2"
